/**
 * summary-generator.ts
 *
 * Generates a Pathfinder summary PDF from personal data and authorization info.
 * Uses pdf-lib to create the PDF from scratch (no template needed).
 */

import { PDFDocument, StandardFonts, rgb, PDFFont, PDFPage } from "pdf-lib";
import type { PersonalData } from "@/lib/types/personal-data";

interface AuthInfo {
  slug: string;
  name: string;
  description: string;
  requirements: string[];
  steps: string[];
  laws: string[];
  exForms: string[];
  deadline: string | null;
}

interface SummaryOptions {
  personalData: PersonalData;
  authorization: AuthInfo;
  lang: string;
}

// ── Constants ───────────────────────────────────────────────────

const MARGIN = 50;
const PAGE_WIDTH = 595.28; // A4
const PAGE_HEIGHT = 841.89;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE_HEIGHT = 16;
const SECTION_GAP = 24;

const COLORS = {
  primary: rgb(0.09, 0.47, 0.82), // #1976d2
  text: rgb(0.13, 0.13, 0.13),
  muted: rgb(0.4, 0.4, 0.4),
  light: rgb(0.93, 0.93, 0.93),
  white: rgb(1, 1, 1),
};

// ── Labels ──────────────────────────────────────────────────────

const L: Record<string, Record<string, string>> = {
  title: {
    es: "RESUMEN DE TRÁMITE",
    en: "PROCEDURE SUMMARY",
    fr: "RÉSUMÉ DE DÉMARCHE",
    ar: "PROCEDURE SUMMARY", // Fallback to English for Arabic (Latin script PDF)
  },
  personalInfo: {
    es: "DATOS PERSONALES", en: "PERSONAL INFORMATION",
    fr: "DONNÉES PERSONNELLES", ar: "PERSONAL INFORMATION",
  },
  authorization: {
    es: "TIPO DE AUTORIZACIÓN", en: "AUTHORIZATION TYPE",
    fr: "TYPE D'AUTORISATION", ar: "AUTHORIZATION TYPE",
  },
  requirements: {
    es: "REQUISITOS", en: "REQUIREMENTS",
    fr: "PRÉREQUIS", ar: "REQUIREMENTS",
  },
  requiredDocs: {
    es: "DOCUMENTOS NECESARIOS", en: "REQUIRED DOCUMENTS",
    fr: "DOCUMENTS NÉCESSAIRES", ar: "REQUIRED DOCUMENTS",
  },
  steps: {
    es: "PASOS A SEGUIR", en: "STEPS TO FOLLOW",
    fr: "ÉTAPES À SUIVRE", ar: "STEPS TO FOLLOW",
  },
  legalBasis: {
    es: "BASE LEGAL", en: "LEGAL BASIS",
    fr: "BASE JURIDIQUE", ar: "LEGAL BASIS",
  },
  forms: {
    es: "FORMULARIOS OFICIALES", en: "OFFICIAL FORMS",
    fr: "FORMULAIRES OFFICIELS", ar: "OFFICIAL FORMS",
  },
  deadline: {
    es: "PLAZO DE RESOLUCIÓN", en: "RESOLUTION DEADLINE",
    fr: "DÉLAI DE RÉSOLUTION", ar: "RESOLUTION DEADLINE",
  },
  disclaimer: {
    es: "AVISO: Este documento es meramente orientativo y no constituye asesoramiento jurídico. Consulte con un profesional antes de realizar cualquier trámite. Documento generado por Pathfinder — Fundació Tierra Digna.",
    en: "NOTICE: This document is for guidance only and does not constitute legal advice. Consult a professional before carrying out any procedure. Document generated by Pathfinder — Fundació Tierra Digna.",
    fr: "AVIS : Ce document est purement indicatif et ne constitue pas un conseil juridique. Consultez un professionnel avant toute démarche. Document généré par Pathfinder — Fundació Tierra Digna.",
    ar: "NOTICE: This document is for guidance only and does not constitute legal advice. Consult a professional before carrying out any procedure. Document generated by Pathfinder — Fundació Tierra Digna.",
  },
  name: { es: "Nombre", en: "Name", fr: "Nom", ar: "Name" },
  dob: { es: "Fecha nacimiento", en: "Date of birth", fr: "Date de naissance", ar: "Date of birth" },
  nationality: { es: "Nacionalidad", en: "Nationality", fr: "Nationalité", ar: "Nationality" },
  document: { es: "Documento", en: "Document", fr: "Document", ar: "Document" },
  nie: { es: "NIE", en: "NIE", fr: "NIE", ar: "NIE" },
  address: { es: "Dirección", en: "Address", fr: "Adresse", ar: "Address" },
  phone: { es: "Teléfono", en: "Phone", fr: "Téléphone", ar: "Phone" },
  email: { es: "Email", en: "Email", fr: "Email", ar: "Email" },
};

function label(key: string, lang: string): string {
  return L[key]?.[lang] || L[key]?.es || key;
}

// ── PDF Builder helpers ─────────────────────────────────────────

class PdfBuilder {
  private doc: PDFDocument;
  private page: PDFPage;
  private font: PDFFont;
  private fontBold: PDFFont;
  private y: number;

  constructor(
    doc: PDFDocument,
    font: PDFFont,
    fontBold: PDFFont,
  ) {
    this.doc = doc;
    this.font = font;
    this.fontBold = fontBold;
    this.page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    this.y = PAGE_HEIGHT - MARGIN;
  }

  private ensureSpace(needed: number) {
    if (this.y - needed < MARGIN) {
      this.page = this.doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      this.y = PAGE_HEIGHT - MARGIN;
    }
  }

  drawHeader(title: string) {
    // Blue bar
    this.page.drawRectangle({
      x: 0, y: PAGE_HEIGHT - 70,
      width: PAGE_WIDTH, height: 70,
      color: COLORS.primary,
    });
    this.page.drawText("PATHFINDER", {
      x: MARGIN, y: PAGE_HEIGHT - 32,
      size: 16, font: this.fontBold, color: COLORS.white,
    });
    this.page.drawText(title, {
      x: MARGIN, y: PAGE_HEIGHT - 52,
      size: 10, font: this.font, color: rgb(0.8, 0.9, 1),
    });
    this.y = PAGE_HEIGHT - 90;
  }

  drawSectionTitle(text: string) {
    this.ensureSpace(SECTION_GAP + LINE_HEIGHT);
    this.y -= SECTION_GAP;
    // Light gray underline
    this.page.drawRectangle({
      x: MARGIN, y: this.y - 2,
      width: CONTENT_WIDTH, height: 1,
      color: COLORS.light,
    });
    this.page.drawText(text, {
      x: MARGIN, y: this.y,
      size: 10, font: this.fontBold, color: COLORS.primary,
    });
    this.y -= LINE_HEIGHT + 4;
  }

  drawKeyValue(key: string, value: string) {
    if (!value) return;
    this.ensureSpace(LINE_HEIGHT);
    this.page.drawText(`${key}:`, {
      x: MARGIN, y: this.y,
      size: 9, font: this.fontBold, color: COLORS.text,
    });
    this.page.drawText(value, {
      x: MARGIN + 130, y: this.y,
      size: 9, font: this.font, color: COLORS.text,
    });
    this.y -= LINE_HEIGHT;
  }

  drawBulletList(items: string[]) {
    for (const item of items) {
      this.ensureSpace(LINE_HEIGHT);
      // Wrap long lines
      const lines = this.wrapText(item, CONTENT_WIDTH - 15, 9);
      for (let i = 0; i < lines.length; i++) {
        this.ensureSpace(LINE_HEIGHT);
        const prefix = i === 0 ? "•  " : "   ";
        this.page.drawText(prefix + lines[i], {
          x: MARGIN + 5, y: this.y,
          size: 9, font: this.font, color: COLORS.text,
        });
        this.y -= LINE_HEIGHT;
      }
    }
  }

  drawParagraph(text: string, size = 8) {
    const lines = this.wrapText(text, CONTENT_WIDTH, size);
    for (const line of lines) {
      this.ensureSpace(LINE_HEIGHT - 2);
      this.page.drawText(line, {
        x: MARGIN, y: this.y,
        size, font: this.font, color: COLORS.muted,
      });
      this.y -= LINE_HEIGHT - 2;
    }
  }

  drawFooter(text: string) {
    this.y -= SECTION_GAP;
    this.ensureSpace(60);
    this.page.drawRectangle({
      x: MARGIN, y: this.y - 2,
      width: CONTENT_WIDTH, height: 1,
      color: COLORS.light,
    });
    this.y -= 8;
    this.drawParagraph(text, 7);
  }

  private wrapText(text: string, maxWidth: number, size: number): string[] {
    const words = text.split(/\s+/);
    const lines: string[] = [];
    let current = "";

    for (const word of words) {
      const test = current ? `${current} ${word}` : word;
      const width = this.font.widthOfTextAtSize(test, size);
      if (width > maxWidth && current) {
        lines.push(current);
        current = word;
      } else {
        current = test;
      }
    }
    if (current) lines.push(current);
    return lines.length > 0 ? lines : [""];
  }
}

// ── Main generator ──────────────────────────────────────────────

export async function generateSummaryPdf(
  options: SummaryOptions
): Promise<Uint8Array> {
  const { personalData: pd, authorization: auth, lang } = options;

  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const builder = new PdfBuilder(doc, font, fontBold);

  // Header
  builder.drawHeader(label("title", lang));

  // Personal data
  builder.drawSectionTitle(label("personalInfo", lang));
  const fullName = [pd.nombre, pd.primerApellido, pd.segundoApellido]
    .filter(Boolean).join(" ");
  builder.drawKeyValue(label("name", lang), fullName);
  if (pd.fechaNacimiento) {
    const [y, m, d] = pd.fechaNacimiento.split("-");
    builder.drawKeyValue(label("dob", lang), `${d}/${m}/${y}`);
  }
  builder.drawKeyValue(label("nationality", lang), pd.nacionalidad);
  if (pd.numeroDocumento) {
    const docLabel = pd.tipoDocumento === "pasaporte" ? "Pasaporte"
      : pd.tipoDocumento === "nie" ? "NIE" : pd.tipoDocumento;
    builder.drawKeyValue(label("document", lang), `${docLabel}: ${pd.numeroDocumento}`);
  }
  if (pd.nie && pd.tipoDocumento !== "nie") {
    builder.drawKeyValue(label("nie", lang), pd.nie);
  }
  const addr = [pd.domicilio, pd.localidad, pd.provincia, pd.codigoPostal]
    .filter(Boolean).join(", ");
  builder.drawKeyValue(label("address", lang), addr);
  builder.drawKeyValue(label("phone", lang), pd.telefono);
  builder.drawKeyValue(label("email", lang), pd.email);

  // Authorization type
  builder.drawSectionTitle(label("authorization", lang));
  builder.drawBulletList([auth.name]);
  if (auth.description) {
    builder.drawBulletList([auth.description]);
  }

  // Required forms
  if (auth.exForms.length > 0) {
    builder.drawSectionTitle(label("forms", lang));
    builder.drawBulletList(auth.exForms.map((f) => `Modelo ${f}`));
  }

  // Requirements
  if (auth.requirements.length > 0) {
    builder.drawSectionTitle(label("requirements", lang));
    builder.drawBulletList(auth.requirements);
  }

  // Steps
  if (auth.steps.length > 0) {
    builder.drawSectionTitle(label("steps", lang));
    auth.steps.forEach((step, i) => {
      builder.drawBulletList([`${i + 1}. ${step}`]);
    });
  }

  // Legal basis
  if (auth.laws.length > 0) {
    builder.drawSectionTitle(label("legalBasis", lang));
    builder.drawBulletList(auth.laws);
  }

  // Deadline
  if (auth.deadline) {
    builder.drawSectionTitle(label("deadline", lang));
    builder.drawBulletList([auth.deadline]);
  }

  // Disclaimer
  builder.drawFooter(label("disclaimer", lang));

  return await doc.save();
}
