/**
 * EX-01 field mapping — re-exports from the canonical source.
 */
export {
  EX_01_TEXT_FIELDS,
  EX_01_SEXO_CHECKBOXES,
  EX_01_TIPO_DOC_CHECKBOXES,
  EX_01_ESTADO_CIVIL_CHECKBOXES,
  EX_01_CIRCUNSTANCIA_CHECKBOXES,
  EX_01_TIPO_AUTORIZACION_CHECKBOXES,
  EX_01_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_01_TITULAR_SEXO_CHECKBOXES,
  EX_01_TITULAR_ESTADO_CIVIL_CHECKBOXES,
  EX_01_CONSENTIMIENTO_CHECKBOX,
  EX_01_DATE_FIELDS,
} from "@/lib/forms/ex-01";
