/**
 * EX-04 field mapping — re-exports from the canonical source.
 */
export {
  EX_04_TEXT_FIELDS,
  EX_04_SEXO_CHECKBOXES,
  EX_04_TIPO_DOC_CHECKBOXES,
  EX_04_ESTADO_CIVIL_CHECKBOXES,
  EX_04_CIRCUNSTANCIA_CHECKBOXES,
  EX_04_TIPO_AUTORIZACION_CHECKBOXES,
  EX_04_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_04_CONSENTIMIENTO_CHECKBOX,
  EX_04_DATE_FIELDS,
} from "@/lib/forms/ex-04";
