/**
 * EX-00 field mapping — re-exports from the canonical source.
 */
export {
  EX_00_TEXT_FIELDS,
  EX_00_SEXO_CHECKBOXES,
  EX_00_TIPO_DOC_CHECKBOXES,
  EX_00_ESTADO_CIVIL_CHECKBOXES,
  EX_00_CIRCUNSTANCIA_CHECKBOXES,
  EX_00_TIPO_AUTORIZACION_CHECKBOXES,
  EX_00_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_00_CONSENTIMIENTO_CHECKBOX,
  EX_00_DATE_FIELDS,
} from "@/lib/forms/ex-00";
