/**
 * EX-07 field mapping — re-exports from the canonical source.
 */
export {
  EX_07_TEXT_FIELDS,
  EX_07_SEXO_CHECKBOXES,
  EX_07_TIPO_DOC_CHECKBOXES,
  EX_07_ESTADO_CIVIL_CHECKBOXES,
  EX_07_CIRCUNSTANCIA_CHECKBOXES,
  EX_07_TIPO_AUTORIZACION_CHECKBOXES,
  EX_07_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_07_CONSENTIMIENTO_CHECKBOX,
  EX_07_DATE_FIELDS,
} from "@/lib/forms/ex-07";
