/**
 * EX-03 field mapping — re-exports from the canonical source.
 */
export {
  EX_03_TEXT_FIELDS,
  EX_03_SEXO_CHECKBOXES,
  EX_03_TIPO_DOC_CHECKBOXES,
  EX_03_ESTADO_CIVIL_CHECKBOXES,
  EX_03_CIRCUNSTANCIA_CHECKBOXES,
  EX_03_TIPO_AUTORIZACION_CHECKBOXES,
  EX_03_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_03_CONSENTIMIENTO_CHECKBOX,
  EX_03_DATE_FIELDS,
} from "@/lib/forms/ex-03";
