/**
 * EX-02 field mapping — re-exports from the canonical source.
 */
export {
  EX_02_TEXT_FIELDS,
  EX_02_SEXO_CHECKBOXES,
  EX_02_TIPO_DOC_CHECKBOXES,
  EX_02_ESTADO_CIVIL_CHECKBOXES,
  EX_02_CIRCUNSTANCIA_CHECKBOXES,
  EX_02_TIPO_AUTORIZACION_CHECKBOXES,
  EX_02_FAMILIAR_SEXO_CHECKBOXES,
  EX_02_FAMILIAR_ESTADO_CIVIL_CHECKBOXES,
  EX_02_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_02_CONSENTIMIENTO_CHECKBOX,
  EX_02_DATE_FIELDS,
} from "@/lib/forms/ex-02";
