/**
 * EX-06 field mapping — re-exports from the canonical source.
 */
export {
  EX_06_TEXT_FIELDS,
  EX_06_SEXO_CHECKBOXES,
  EX_06_TIPO_DOC_CHECKBOXES,
  EX_06_ESTADO_CIVIL_CHECKBOXES,
  EX_06_CIRCUNSTANCIA_CHECKBOXES,
  EX_06_TIPO_AUTORIZACION_CHECKBOXES,
  EX_06_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_06_CONSENTIMIENTO_CHECKBOX,
  EX_06_DATE_FIELDS,
} from "@/lib/forms/ex-06";
