/**
 * EX-09 field mapping — re-exports from the canonical source.
 */
export {
  EX_09_TEXT_FIELDS,
  EX_09_SEXO_CHECKBOXES,
  EX_09_TIPO_DOC_CHECKBOXES,
  EX_09_ESTADO_CIVIL_CHECKBOXES,
  EX_09_CIRCUNSTANCIA_CHECKBOXES,
  EX_09_TIPO_AUTORIZACION_CHECKBOXES,
  EX_09_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_09_CONSENTIMIENTO_CHECKBOX,
  EX_09_DATE_FIELDS,
} from "@/lib/forms/ex-09";
