/**
 * EX-11 field mapping — re-exports from the canonical source.
 */
export {
  EX_11_TEXT_FIELDS,
  EX_11_SEXO_CHECKBOXES,
  EX_11_TIPO_DOC_CHECKBOXES,
  EX_11_ESTADO_CIVIL_CHECKBOXES,
  EX_11_CIRCUNSTANCIA_CHECKBOXES,
  EX_11_TIPO_AUTORIZACION_CHECKBOXES,
  EX_11_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_11_CONSENTIMIENTO_CHECKBOX,
  EX_11_DATE_FIELDS,
} from "@/lib/forms/ex-11";
