/**
 * EX-10 field mapping — re-exports from the canonical source.
 */
export {
  EX_10_TEXT_FIELDS,
  EX_10_SEXO_CHECKBOXES,
  EX_10_TIPO_DOC_CHECKBOXES,
  EX_10_ESTADO_CIVIL_CHECKBOXES,
  EX_10_FAMILIAR_SEXO_CHECKBOXES,
  EX_10_FAMILIAR_ESTADO_CIVIL_CHECKBOXES,
  EX_10_FORMACIO_TIPUS_CHECKBOXES,
  EX_10_FORMACIO_MODALITAT_CHECKBOXES,
  EX_10_CIRCUNSTANCIA_CHECKBOXES,
  EX_10_TIPO_AUTORIZACION_CHECKBOXES,
  EX_10_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_10_CONSENTIMIENTO_CHECKBOX,
  EX_10_DATE_FIELDS,
} from "@/lib/forms/ex-10";
