/**
 * EX-19 field mapping — re-exports from the canonical source.
 */
export {
  EX_19_TEXT_FIELDS,
  EX_19_SEXO_CHECKBOXES,
  EX_19_TIPO_DOC_CHECKBOXES,
  EX_19_ESTADO_CIVIL_CHECKBOXES,
  EX_19_CIRCUNSTANCIA_CHECKBOXES,
  EX_19_TIPO_AUTORIZACION_CHECKBOXES,
  EX_19_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_19_CONSENTIMIENTO_CHECKBOX,
  EX_19_DATE_FIELDS,
} from "@/lib/forms/ex-19";
