/**
 * EX-25 field mapping — re-exports from the canonical source.
 */
export {
  EX_25_TEXT_FIELDS,
  EX_25_SEXO_CHECKBOXES,
  EX_25_TIPO_DOC_CHECKBOXES,
  EX_25_ESTADO_CIVIL_CHECKBOXES,
  EX_25_CIRCUNSTANCIA_CHECKBOXES,
  EX_25_TIPO_AUTORIZACION_CHECKBOXES,
  EX_25_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_25_CONSENTIMIENTO_CHECKBOX,
  EX_25_DATE_FIELDS,
} from "@/lib/forms/ex-25";
