/**
 * EX-24 field mapping — re-exports from the canonical source.
 */
export {
  EX_24_TEXT_FIELDS,
  EX_24_SEXO_CHECKBOXES,
  EX_24_TIPO_DOC_CHECKBOXES,
  EX_24_ESTADO_CIVIL_CHECKBOXES,
  EX_24_CIRCUNSTANCIA_CHECKBOXES,
  EX_24_TIPO_AUTORIZACION_CHECKBOXES,
  EX_24_ESPANYOL_SEXO_CHECKBOXES,
  EX_24_ESPANYOL_ESTADO_CIVIL_CHECKBOXES,
  EX_24_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_24_CONSENTIMIENTO_CHECKBOX,
  EX_24_DATE_FIELDS,
} from "@/lib/forms/ex-24";
