/** EX-32 field mapping — re-exports from the canonical source. */
export {
  EX_32_TEXT_FIELDS,
  EX_32_SEXO_CHECKBOXES,
  EX_32_TIPO_DOC_CHECKBOXES,
  EX_32_ESTADO_CIVIL_CHECKBOXES,
  EX_32_CIRCUNSTANCIA_CHECKBOXES,
  EX_32_TIPO_AUTORIZACION_CHECKBOXES,
  EX_32_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_32_CONSENTIMIENTO_CHECKBOX,
  EX_32_DATE_FIELDS,
} from "@/lib/forms/ex-32";
