/** EX-31 field mapping — re-exports from the canonical source. */
export {
  EX_31_TEXT_FIELDS,
  EX_31_SEXO_CHECKBOXES,
  EX_31_TIPO_DOC_CHECKBOXES,
  EX_31_ESTADO_CIVIL_CHECKBOXES,
  EX_31_CIRCUNSTANCIA_CHECKBOXES,
  EX_31_TIPO_AUTORIZACION_CHECKBOXES,
  EX_31_HIJOS_ESCOLARIZACION_CHECKBOXES,
  EX_31_CONSENTIMIENTO_CHECKBOX,
  EX_31_DATE_FIELDS,
} from "@/lib/forms/ex-31";
