/**
 * scripts/label-ex31.ts
 *
 * Two outputs:
 *  1. public/forms/EX-31-labeled.pdf — the template with each field's name
 *     drawn in red at its position, so a human can open it and verify the
 *     field→data mapping visually.
 *  2. docs/ex31-field-positions.md — a reading-order table (page, x, y, name)
 *     so we can infer the section each field belongs to.
 *
 * Read-only against the source PDF. Run:
 *   npx tsx scripts/label-ex31.ts
 */

import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";

interface FieldPos {
  name: string;
  page: number; // 1-indexed
  x: number;
  y: number;
  w: number;
  h: number;
  type: string;
}

async function main() {
  const srcPath = join(process.cwd(), "public", "forms", "EX-31.pdf");
  const bytes = readFileSync(srcPath);
  const pdf = await PDFDocument.load(bytes);
  const form = pdf.getForm();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const pages = pdf.getPages();

  const positions: FieldPos[] = [];

  for (const field of form.getFields()) {
    const name = field.getName();
    const type = field.constructor.name;
    const widgets = field.acroField.getWidgets();
    for (const w of widgets) {
      const rect = w.getRectangle();
      // Find page index for this widget
      let pageIndex = 0;
      const pageRef = w.P();
      for (let i = 0; i < pages.length; i++) {
        if (pages[i].ref === pageRef) {
          pageIndex = i;
          break;
        }
      }
      positions.push({
        name,
        page: pageIndex + 1,
        x: Math.round(rect.x),
        y: Math.round(rect.y),
        w: Math.round(rect.width),
        h: Math.round(rect.height),
        type,
      });

      // Draw the field name label in red at the widget origin
      const page = pages[pageIndex];
      const short = name
        .replace("Casilla de verificación", "C")
        .replace("Texto", "T");
      page.drawText(short, {
        x: rect.x + 1,
        y: rect.y + 1,
        size: 6,
        font,
        color: rgb(0.85, 0, 0),
      });
    }
  }

  // Labeled PDF
  const outPdf = join(process.cwd(), "public", "forms", "EX-31-labeled.pdf");
  const labeledBytes = await pdf.save();
  writeFileSync(outPdf, labeledBytes);
  console.log(`✓ Labeled PDF: ${outPdf}`);

  // Positions report — reading order: page asc, y desc (top first), x asc
  positions.sort((a, b) => {
    if (a.page !== b.page) return a.page - b.page;
    if (Math.abs(a.y - b.y) > 8) return b.y - a.y;
    return a.x - b.x;
  });

  const lines: string[] = [];
  lines.push("# EX-31 field positions (reading order)");
  lines.push("");
  lines.push("Auto-generated by `scripts/label-ex31.ts`. Use alongside");
  lines.push("`public/forms/EX-31-labeled.pdf` to build the field map in");
  lines.push("`lib/forms/ex-31.ts`.");
  lines.push("");
  let currentPage = 0;
  for (const p of positions) {
    if (p.page !== currentPage) {
      currentPage = p.page;
      lines.push(`\n## Page ${p.page}\n`);
      lines.push("| Field | Type | x | y | w×h |");
      lines.push("|-------|------|---|---|-----|");
    }
    lines.push(
      `| ${p.name} | ${p.type.replace("PDF", "")} | ${p.x} | ${p.y} | ${p.w}×${p.h} |`
    );
  }

  const outMd = join(process.cwd(), "docs", "ex31-field-positions.md");
  mkdirSync(dirname(outMd), { recursive: true });
  writeFileSync(outMd, lines.join("\n") + "\n", "utf-8");
  console.log(`✓ Positions report: ${outMd}`);
  console.log(`  ${positions.length} widgets across ${pages.length} pages`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
