import { fillExForm } from "../lib/pdf/form-filler";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

async function main() {
const OUT = join(process.cwd(), "output");
mkdirSync(OUT, { recursive: true });

const sample = {
  pasaporte: "AB123456",
  nie: "X1234567Z",
  primerApellido: "García",
  segundoApellido: "López",
  nombre: "Mohamed",
  fechaNacimiento: "1990-05-15",
  lugarNacimiento: "Casablanca",
  paisNacimiento: "Marruecos",
  nacionalidad: "Marroquí",
  sexo: "H" as const,
  estadoCivil: "soltero" as const,
  tipoDocumento: "pasaporte" as const,
  numeroDocumento: "AB123456",
  nombrePadre: "Ahmed García",
  nombreMadre: "Fátima López",
  domicilio: "Calle Mayor",
  numeroDomicilio: "10",
  pisoDomicilio: "2A",
  localidad: "Barcelona",
  codigoPostal: "08001",
  provincia: "Barcelona",
  telefono: "612345678",
  email: "mohamed@example.com",
  representanteLegal: "Ana Martínez",
  representanteDniNiePas: "Y9876543X",
  representanteTitulo: "Abogada",
  hijosEscolarizacion: true,
  familiar_pasaporte: "CD789012",
  familiar_nie: "Y7654321B",
  familiar_primerApellido: "García",
  familiar_segundoApellido: "Martín",
  familiar_nombre: "Aicha",
  familiar_fechaNacimiento: "1992-03-20",
  familiar_lugarNacimiento: "Rabat",
  familiar_paisNacimiento: "Marruecos",
  familiar_nacionalidad: "Marroquí",
  familiar_sexo: "M" as const,
  familiar_estadoCivil: "casado" as const,
  familiar_nombrePadre: "Omar García",
  familiar_nombreMadre: "Khadija Martín",
  familiar_domicilio: "Calle Mayor",
  familiar_numeroDomicilio: "10",
  familiar_pisoDomicilio: "2A",
  familiar_localidad: "Barcelona",
  familiar_codigoPostal: "08001",
  familiar_provincia: "Barcelona",
  familiar_vinculo: "Cónyuge",
  familiar_parentesco: "Cónyuge",
  titular_pasaporte: "EF345678",
  titular_nie: "Z1122334C",
  titular_primerApellido: "Rodríguez",
  titular_segundoApellido: "Sánchez",
  titular_nombre: "Carlos",
  titular_sexo: "H" as const,
  titular_estadoCivil: "casado" as const,
  titular_fechaNacimiento: "1985-07-10",
  titular_paisNacimiento: "España",
  titular_nombrePadre: "Luis Rodríguez",
  titular_nombreMadre: "Carmen Sánchez",
  titular_parentesco: "Cónyuge",
  espanyol_pasaporte: "GH901234",
  espanyol_dni: "12345678A",
  espanyol_primerApellido: "Martínez",
  espanyol_segundoApellido: "Pérez",
  espanyol_nombre: "Laura",
  espanyol_sexo: "M" as const,
  espanyol_estadoCivil: "casado" as const,
  espanyol_fechaNacimiento: "1988-11-25",
  espanyol_paisNacimiento: "España",
  espanyol_nombrePadre: "José Martínez",
  espanyol_nombreMadre: "María Pérez",
  espanyol_domicilio: "Avenida Diagonal",
  espanyol_numeroDomicilio: "100",
  espanyol_pisoDomicilio: "3B",
  espanyol_localidad: "Barcelona",
  espanyol_codigoPostal: "08005",
  espanyol_provincia: "Barcelona",
  espanyol_parentesco: "Cónyuge",
  ciudadanoUE_pasaporte: "IJ567890",
  ciudadanoUE_nie: "W5544332D",
  ciudadanoUE_primerApellido: "Müller",
  ciudadanoUE_segundoApellido: "Schmidt",
  ciudadanoUE_nombre: "Hans",
  ciudadanoUE_nacionalidad: "Alemana",
  ciudadanoUE_domicilio: "Calle Provença",
  ciudadanoUE_numeroDomicilio: "200",
  ciudadanoUE_pisoDomicilio: "1A",
  ciudadanoUE_localidad: "Barcelona",
  ciudadanoUE_codigoPostal: "08008",
  ciudadanoUE_provincia: "Barcelona",
  empleador_nombre: "Construcciones García SL",
  empleador_nifNie: "B12345678",
  empleador_actividad: "Construcción",
  empleador_ocupacion: "Peón de obra",
  empleador_cnae: "4120",
  empleador_cnoSpe: "9600",
  empleador_domicilio: "Polígono Industrial Norte",
  empleador_numero: "5",
  empleador_piso: "Nave 3",
  empleador_localidad: "Badalona",
  empleador_codigoPostal: "08911",
  empleador_provincia: "Barcelona",
  empleador_telefono: "934567890",
  empleador_email: "rrhh@construccionesgarcía.es",
  empleador_repNombre: "Pedro García",
  empleador_repDniNie: "23456789B",
  empleador_repTitulo: "Administrador único",
  entitat_nombre: "Instituto Tecnológico BCN",
  entitat_nifNie: "Q1234567A",
  entitat_actividad: "Formación profesional",
  entitat_ocupacion: "Técnico informático",
  entitat_domicilio: "Carrer de Pallars",
  entitat_numero: "80",
  entitat_piso: "Planta 1",
  entitat_localidad: "Barcelona",
  entitat_codigoPostal: "08018",
  entitat_provincia: "Barcelona",
  entitat_telefono: "932345678",
  entitat_email: "info@itbcn.es",
  entitat_repNombre: "Marta Puig",
  entitat_repDniNie: "34567890C",
  entitat_repTitulo: "Directora",
  activitat_razonSocial: "Servicios Digitales Mohamed SL",
  activitat_nif: "B87654321",
  activitat_actividad: "Desarrollo web y consultoría",
  activitat_domicilio: "Carrer de Provença",
  activitat_numero: "150",
  activitat_piso: "4t 2a",
  activitat_localidad: "Barcelona",
  activitat_codigoPostal: "08008",
  activitat_provincia: "Barcelona",
  activitat_telefono: "611223344",
  activitat_email: "mohamed@servicesdigitals.es",
  tutor_naturaleza: "Entidad pública",
  tutor_relacionMenor: "Tutor legal",
  tutor_nombre: "Generalitat de Catalunya - DGAIA",
  tutor_dniNiePas: "Q0801175A",
  tutor_domicilio: "Carrer de Ferlandina",
  tutor_numero: "8",
  tutor_piso: "",
  tutor_localidad: "Barcelona",
  tutor_codigoPostal: "08001",
  tutor_provincia: "Barcelona",
  tutor_telefono: "934537700",
  tutor_email: "dgaia@gencat.cat",
  tutor_repNombre: "Josep Vila",
  tutor_repDniNie: "45678901D",
  tutor_repTitulo: "Director",
  repPresentacion_nombre: "Ana Martínez Abogados SLP",
  repPresentacion_dniNiePas: "Y9876543X",
  repPresentacion_domicilio: "Carrer de Balmes",
  repPresentacion_numero: "45",
  repPresentacion_piso: "2n 1a",
  repPresentacion_localidad: "Barcelona",
  repPresentacion_codigoPostal: "08007",
  repPresentacion_provincia: "Barcelona",
  repPresentacion_telefono: "932109876",
  repPresentacion_email: "ana@martinezabogados.es",
  repPresentacion_repLegal: "Ana Martínez",
  repPresentacion_repDniNiePas: "Y9876543X",
  repPresentacion_repTitulo: "Abogada",
  notif_nombre: "Ana Martínez Abogados SLP",
  notif_dniNiePas: "Y9876543X",
  notif_domicilio: "Carrer de Balmes",
  notif_numero: "45",
  notif_piso: "2n 1a",
  notif_localidad: "Barcelona",
  notif_codigoPostal: "08007",
  notif_provincia: "Barcelona",
  notif_telefono: "932109876",
  notif_email: "ana@martinezabogados.es",
  formacio_entitat: "Institut de Formació Professional",
  formacio_nom: "Certificat Professional Informàtica",
  formacio_codigoCurs: "IFCT0210",
  formacio_nifCif: "Q0801175A",
  formacio_direccio: "Carrer de Pallars 80",
  formacio_provincia: "Barcelona",
  formacio_duracio: "600",
  formacio_fechaInici: "2024-09-01",
  formacio_fechaFi: "2025-06-30",
  formacio_tipus: ["certificat_professional"] as string[],
  formacio_modalitat: ["presencial"] as string[],
};

const forms: Array<{ id: string; slug: string }> = [
  { id: "EX-00", slug: "estancia_estudis_superiors" },
  { id: "EX-01", slug: "residencia_no_lucrativa" },
  { id: "EX-02", slug: "reagrupacio_familiar" },
  { id: "EX-03", slug: "treball_compte_alie_inicial" },
  { id: "EX-04", slug: "residencia_practiques" },
  { id: "EX-06", slug: "treball_temporada" },
  { id: "EX-07", slug: "treball_compte_propi_inicial" },
  { id: "EX-09", slug: "residencia_excepcio_treball" },
  { id: "EX-10", slug: "arraigo_social" },
  { id: "EX-11", slug: "residencia_llarga_duracio_nacional" },
  { id: "EX-19", slug: "targeta_familiar_ciutada_ue" },
  { id: "EX-24", slug: "residencia_familiar_espanyol" },
  { id: "EX-25", slug: "menor_acompanyat_nascut_espanya" },
];

const results: Array<{ form: string; status: string; kb: string }> = [];

for (const { id, slug } of forms) {
  try {
    const bytes = await fillExForm(id as any, sample, slug);
    if (!bytes) {
      results.push({ form: id, status: "NULL", kb: "0" });
      continue;
    }
    const out = join(OUT, `${id}-filled.pdf`);
    writeFileSync(out, bytes);
    results.push({
      form: id,
      status: "OK",
      kb: (bytes.length / 1024).toFixed(1)
    });
  } catch (e: any) {
    results.push({
      form: id,
      status: `ERROR: ${e.message?.slice(0, 40)}`,
      kb: "0"
    });
  }
}

console.log("\n" + "─".repeat(55));
console.log("Form       Status                               KB");
console.log("─".repeat(55));
for (const r of results) {
  console.log(
    `${r.form.padEnd(10)} ${r.status.padEnd(37)} ${r.kb}`
  );
}
console.log("─".repeat(55));
}

main().catch(console.error);
